#!/usr/bin/env python3
"""Generate _version.py from git describe.

Run this script before building or installing the package.
The generated file is untracked (.gitignore) and should be
regenerated on every build/install.
"""

import os
import re
import subprocess
import sys


def generate():
    repo_root = os.path.dirname(os.path.abspath(__file__))
    # Walk up to the git root (two levels above tools/tdm-audio-bridge/)
    git_root = os.path.join(repo_root, '..', '..')

    try:
        raw = subprocess.check_output(
            ['git', 'describe', '--tags', '--always', '--dirty'],
            cwd=git_root,
            stderr=subprocess.DEVNULL,
        ).decode().strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        raw = 'unknown'

    # Parse: v2.2.0-24-gabcdef1-dirty  or  v2.2.0  or  abcdef1
    tag = raw
    commits = '0'
    git_hash = ''
    dirty = 'dirty' in raw

    # Full tag+commits+hash pattern: vX.Y.Z-N-gHASH[-dirty]
    m = re.match(r'^(v[\d.]+)-(\d+)-g([0-9a-f]+)(?:-dirty)?$', raw)
    if m:
        tag = m.group(1)
        commits = m.group(2)
        git_hash = m.group(3)
    else:
        # Exact tag: vX.Y.Z[-dirty]
        m = re.match(r'^(v[\d.]+)(?:-dirty)?$', raw)
        if m:
            tag = m.group(1)
            git_hash = ''
            commits = '0'
        else:
            # Bare hash (no tags): abcdef1[-dirty]
            m = re.match(r'^([0-9a-f]+)(?:-dirty)?$', raw)
            if m:
                tag = 'v0.0.0'
                git_hash = m.group(1)

    out_path = os.path.join(repo_root, 'tdm_audio_bridge', '_version.py')
    with open(out_path, 'w') as f:
        f.write(f'# Auto-generated by gen_version.py - do not edit\n')
        f.write(f'VERSION = {raw!r}\n')
        f.write(f'GIT_TAG = {tag!r}\n')
        f.write(f'GIT_COMMITS = {commits!r}\n')
        f.write(f'GIT_HASH = {git_hash!r}\n')
        f.write(f'GIT_DIRTY = {dirty!r}\n')

    print(f'Wrote {out_path}: {raw}')


if __name__ == '__main__':
    generate()
